2022-07-24 13:17:52,960 INFO: Microblog startup [in C:\Users\Pho\Documents\codes\Python-Projects\microblog\app\__init__.py:28]
2022-07-24 13:18:52,303 ERROR: Exception on /edit_profile [POST] [in C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\app\routes.py", line 102, in edit_profile
    db.session.commit()
  File "<string>", line 2, in commit
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3383, in flush
    self._flush(objects)
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3522, in _flush
    with util.safe_reraise():
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3483, in _flush
    flush_context.execute()
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 237, in save_obj
    _emit_update_statements(
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1001, in _emit_update_statements
    c = connection._execute_20(
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Pho\Documents\codes\Python-Projects\microblog\venv\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('chief', 'Real name is chief, master chief spartan officer John 117', 2)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-07-24 13:31:35,726 INFO: Microblog startup [in C:\Users\Pho\Documents\codes\Python-Projects\microblog\app\__init__.py:28]
2022-07-24 13:34:18,654 INFO: Microblog startup [in C:\Users\Pho\Documents\codes\Python-Projects\microblog\app\__init__.py:28]
2022-07-24 13:34:45,217 INFO: Microblog startup [in C:\Users\Pho\Documents\codes\Python-Projects\microblog\app\__init__.py:28]
2022-07-24 14:18:58,100 INFO: Microblog startup [in C:\Users\Pho\Documents\codes\Python-Projects\microblog\app\__init__.py:28]
2022-07-24 14:19:19,624 INFO: Microblog startup [in C:\Users\Pho\Documents\codes\Python-Projects\microblog\app\__init__.py:28]
2022-07-24 14:23:56,027 INFO: Microblog startup [in C:\Users\Pho\Documents\codes\Python-Projects\microblog\app\__init__.py:28]
2022-07-24 14:35:27,556 INFO: Microblog startup [in C:\Users\Pho\Documents\codes\Python-Projects\microblog\app\__init__.py:28]
2022-07-24 23:07:58,744 INFO: Microblog startup [in C:\Users\masterchief\Documents\Codes\Python\Flask-Projects\microblog\app\__init__.py:49]
2022-07-25 23:00:46,093 INFO: Microblog startup [in C:\Users\masterchief\Documents\Codes\Python\Flask-Projects\microblog\app\__init__.py:49]
2022-07-25 23:04:36,512 INFO: Microblog startup [in C:\Users\masterchief\Documents\Codes\Python\Flask-Projects\microblog\app\__init__.py:49]
2022-07-25 23:09:34,577 INFO: Microblog startup [in C:\Users\masterchief\Documents\Codes\Python\Flask-Projects\microblog\app\__init__.py:49]
2022-07-25 23:13:10,351 INFO: Microblog startup [in C:\Users\masterchief\Documents\Codes\Python\Flask-Projects\microblog\app\__init__.py:49]
